### PR TITLE
Fix Readme.md heartbeat example

### PR DESCRIPTION
**Pull request by miltondts**

### CODE REVIEW

**Comment by gertjana** [comment]
thx ;)

**Comment by MaxWagener** [comment]
@gertjana is the project still actively maintained? Would be great as the tool itself works great - but a single issue while sending meter values kill my whole use case (and while trying hard I have not been able to solve it on my own)

**Comment by gertjana** [comment]
It is, we are using it ourselves, could you please raise an issue, including steps to reproduce. 
then we can see if we can fix it

**Comment by MaxWagener** [comment]
@gertjana Issues are disabled for the project as it seems - but will paste it here ... Thanks for giving a hint :)

**Problem:** Whenever I try to send meter values as RAW it's sent without the Format at all. When sending as SignedData it works.

**Script for sending meter values:**
  send(MeterValuesReq(scope = ConnectorScope(1),     
              transactionId = Option(transId), 
              meters = List(meter.Meter(timestamp = ZonedDateTime.now(), 
                                        values = List(meter.Value(value = "310", 
                                                                  context = meter.ReadingContext.SamplePeriodic, 
                                                                  format = meter.ValueFormat.Raw, 
                                                                  measurand = meter.Measurand.EnergyActiveImportRegister, 
                                                                  phase = None, 
                                                                  location = meter.Location.Outlet, 
                                                                  unit = meter.UnitOfMeasure.Kwh), 
                                                      meter.Value(value = "6475.9", 
                                                                  context = meter.ReadingContext.SamplePeriodic, 
                                                                  format = meter.ValueFormat.Raw, 
                                                                  measurand = meter.Measurand.PowerActiveImport, 
                                                                  phase = None, 
                                                                  location = meter.Location.Outlet, 
                                                                  unit = meter.UnitOfMeasure.W)
                                                                  )))))
**Log Docile Charge Point:**
MeterValuesReq(ConnectorScope(1),Some(69),List(Meter(2019-09-26T08:27:34.578Z[UTC],List(Value(310,SamplePeriodic,Raw,EnergyActiveImportRegister,None,Outlet,Kwh), Value(6475.9,SamplePeriodic,Raw,PowerActiveImport,None,Outlet,W)))))

**Log Central System:**
2019-09-26 08:27:34.822 DEBUG [   OCPP  REQUEST VERSION_1_6    WS] [ DefaultWorker-41] o.Ocpp16CentralSystemWebSocketController  [00000000-0000-0000-1111-000000020000]: Got web socket message: [2,"9","MeterValues",{"connectorId":2,"transactionId":69,"meterValue":[{"timestamp":"2019-09-26T08:27:34.578Z","sampledValue":[{"value":"310","unit":"kWh"},{"value":"6475.9","measurand":"Power.Active.Import","unit":"W"}]}]}]
2019-09-26 08:27:34.863 ERROR [   OCPP  REQUEST VERSION_1_6    WS] [ DefaultWorker-41] o.Ocpp16CentralSystemWebSocketController  [00000000-0000-0000-1111-000000020000]: Failed to handle web socket request: OcppCentralSystemWebSocketRequestMessage(chargePointId=00000000-0000-0000-1111-000000020000, chargeBoxIdentifier=LOAD_TEST_000002, messageId=9, payload={"connectorId":2,"transactionId":69,"meterValue":[{"timestamp":"2019-09-26T08:27:34.578Z","sampledValue":[{"value":"310","unit":"kWh"},{"value":"6475.9","measurand":"Power.Active.Import","unit":"W"}]}]}, action=METER_VALUES)

**Comment by reinierl** [comment]
I think that's by design. The "format" field is considered have a value of "Raw" by default. If you specify "Raw" in the Scala version of the message, the OCPP library will serialize the message to a JSON string that does not have the "format" field at all. According to  the OCPP standard, it should be handled the same way by the Central System anyway.

We have unit tests on the OCPP library that check that the generated JSON matches the schema files from the Open Charge Alliance.

I think we have discovered a bug in your Central System here.

**Comment by MaxWagener** [comment]
@reinierl Thanks for the quick feedback - Got it and found it in the OCPP docs as well - Guess we need to fix that :) Thanks again + kudos for the docile-charge-point!
From the OCPP Docs -> The EXPERIMENTAL **optional** format field specifies whether the data is represented in the normal **(default)** form as a simple numeric value ("Raw"), or as "SignedData", an opaque digitally signed binary data block, represented as hex data.

**Comment by reinierl** [comment]
@MaxWagener  Thanks for using the tool! I've enabled issues on the project now, so you or others can report bugs in a better way from now on.

**Pull request merged**
